### ISSUE TITLE
Conduct Tab pulling wrong end and start dates of consequence

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Students#12]
When clicking on a student in the student app and navigating to conduct, the start of consequence column is actually pulling the end date and the end day of consequence is pulling nothing.
![2017-08-31_10-13-08](https://user-images.githubusercontent.com/16708913/29927670-0a66786a-8e35-11e7-9a91-bcce2db25cd0.png)

**Comment by hcsdrose** [comment]
Fixed in latest release.
